export const GET_RECIPES = 'GET_RECIPES'
export const GET_DIETS = 'GET_DIETS'
export const GET_DETAIL = 'GET_DETAIL'
export const RESET_DETAIL = 'RESET_DETAIL'
export const FILTER_ORIGIN = 'FILTER_ORIGIN'
export const FILTER_DIET = 'FILTER_DIET'
export const ORDER_SCORE = 'ORDER_SCORE'
export const ORDER_NAME = 'ORDER_NAME'